# Generated by Django 5.2.6 on 2026-01-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_document_partner_paymenttransaction_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('tiempo_preparacion', models.IntegerField(default=15, help_text='Tiempo en minutos')),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('alergenos', models.CharField(blank=True, help_text='Ingredientes alergénicos separados por comas', max_length=255, null=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('sin_gluten', models.BooleanField(default=False)),
                ('picante', models.BooleanField(default=False)),
                ('nivel_picante', models.IntegerField(choices=[(0, 'Nivel 0'), (1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=0)),
                ('ingredientes', models.TextField(blank=True, help_text='Ingredientes separados por comas', null=True)),
                ('stock', models.IntegerField(default=999)),
                ('oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='api_rest.categoria')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'platos',
                'ordering': ['nombre'],
            },
        ),
    ]
